### ISSUE TITLE
HTML table formatting

### ISSUE THREAD

**Issue by chadbunn** [DimitarChristoff/doctor#4]
When I run MD Doctor my tables get formatted improperly.  I have a table in .md that is formatted like this:  

|Version|Polygon|Multi-Polygon|Point|Multi-Point|Line
|----------|-------|-------------|-----|-----------|-------
|Standalone|   x   |   x   |  x    |       |
|Add-In    |   x   |       |  x    |  x    |  x  

but the field names get cut off once processed and in HTML.  Not sure if I am causing the issue with bad .md formatting or if Doctor does not handle tables well.

**Comment by DimitarChristoff** [comment]
tables and any markdown conversion is handled by an npm dependency called
"marked". can you provide a sample of the md hat gets created badly so we
can confirm it?

On Wednesday, March 4, 2015, Chad Bunn <notifications@github.com> wrote:

> When I run MD Doctor my tables get formatted improperly. I have a table in
> .md that is formatted like this:
>   Version Polygon Multi-Polygon Point Multi-Point Line   Standalone x x x
> Add-In x x x x
>
> but the field names get cut off once processed and in HTML. Not sure if I
> am causing the issue with bad .md formatting or if Doctor does not handle
> tables well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DimitarChristoff/doctor/issues/4>.
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by chadbunn** [comment]
|Version|Polygon|Multi-Polygon|Point|Multi-Point|Line
|----------|-------|-------------|-----|-----------|-------
|Standalone|   x   |   x   |  x    |       |
|Add-In    |   x   |       |  x    |  x    |  x  

this is the table that is getting formatted badly.  my entire .md is [here:](https://github.com/SLUGIS/CMGuide)

**Comment by DimitarChristoff** [comment]
it works but the tables produced are not formatted due to missing classes `table table-striped`. gonna add support for that easily - also, had to replace empty cells with `&nbsp;`

**Comment by DimitarChristoff** [comment]
fixed by b15b5f2..e434b0b, 0.2.6 out on npm
