### ISSUE TITLE
Missing licensing for files distributed with generated documentation

### ISSUE THREAD

**Issue by jakub-skowron-s** [DimitarChristoff/doctor#5]
What is the license for files in build/ directory, i.e.:
- doctor.js
- doctor.css
- prettify.js
- lang-css.js
and others?

Is it possible to redistribute these files with the generated documentation on any license? Please add licensing information to the files.
Is is public domain or CC0 https://creativecommons.org/publicdomain/zero/1.0/ ?

**Comment by DimitarChristoff** [comment]
- doctor and any related files written by me are MIT
- prettify is not. https://github.com/google/code-prettify/blob/master/package.json#L5 - Apache 2.0
- lang-css belongs to prettify
- ACE (if you use it) is now BSD, though version I have is the old GPL
- mootools is MIT
- scrollspy is MIT (also written by me)
